# Generated by Django 4.0.1 on 2022-01-12 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imoveis',
            new_name='Imovei',
        ),
    ]
